#!/usr/bin/env bash
# Generate secrets/.env from current environment variables
# Usage: ./scripts/generate-env.sh [--force]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/secrets/.env"

# Parse arguments
FORCE=false
for arg in "$@"; do
    case $arg in
        --force|-f) FORCE=true ;;
        --help|-h)
            echo "Usage: $0 [--force]"
            echo "Generate secrets/.env from current environment variables"
            echo ""
            echo "Options:"
            echo "  --force, -f  Overwrite existing secrets/.env"
            exit 0
            ;;
    esac
done

# Check for existing file
if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != "true" ]]; then
    echo "Error: $ENV_FILE already exists. Use --force to overwrite."
    exit 1
fi

# Ensure secrets directory exists
mkdir -p "$PROJECT_DIR/secrets"

# Check required variables
MISSING=()
[[ -z "${CONFLUENCE_API_TOKEN:-}" ]] && MISSING+=("CONFLUENCE_API_TOKEN")
[[ -z "${CONFLUENCE_EMAIL:-}" ]] && MISSING+=("CONFLUENCE_EMAIL")
[[ -z "${CONFLUENCE_SITE_URL:-}" ]] && MISSING+=("CONFLUENCE_SITE_URL")
[[ -z "${JIRA_API_TOKEN:-}" ]] && MISSING+=("JIRA_API_TOKEN")
[[ -z "${JIRA_EMAIL:-}" ]] && MISSING+=("JIRA_EMAIL")
[[ -z "${JIRA_SITE_URL:-}" ]] && MISSING+=("JIRA_SITE_URL")

if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "Warning: Missing environment variables:"
    for var in "${MISSING[@]}"; do
        echo "  - $var"
    done
    echo ""
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Yy]$ ]] && exit 1
fi

# Generate SESSION_SECRET if not set
SESSION_SECRET="${SESSION_SECRET:-$(openssl rand -hex 32)}"

# Write the file
cat > "$ENV_FILE" << EOF
# Generated by scripts/generate-env.sh on $(date -Iseconds)
# Platforms
ENABLED_PLATFORMS=${ENABLED_PLATFORMS:-confluence,jira,splunk}

# Session
SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT_MINUTES:-60}
MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-10}
SESSION_SECRET=${SESSION_SECRET}

# Claude Authentication
CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN:-}

# Confluence
CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN:-}
CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL:-}
CONFLUENCE_SITE_URL=${CONFLUENCE_SITE_URL:-}
DEMO_SPACE_KEY=${DEMO_SPACE_KEY:-CDEMO}

# JIRA
JIRA_API_TOKEN=${JIRA_API_TOKEN:-}
JIRA_EMAIL=${JIRA_EMAIL:-}
JIRA_SITE_URL=${JIRA_SITE_URL:-}
DEMO_PROJECT_KEY=${DEMO_PROJECT_KEY:-DEMO}

# Splunk (defaults work for local dev with 'make dev-full')
SPLUNK_URL=${SPLUNK_URL:-https://splunk:8089}
SPLUNK_USERNAME=${SPLUNK_USERNAME:-admin}
SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-DemoPass123!}
SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN:-demo-hec-token-12345}

# Domain (for production)
DOMAIN=${DOMAIN:-demo.assistant-skills.dev}
EOF

# Set secure permissions
chmod 600 "$ENV_FILE"

echo "Created $ENV_FILE"
echo ""
echo "Configured platforms:"
grep -E '^(CONFLUENCE|JIRA|SPLUNK)_(SITE_URL|URL)=' "$ENV_FILE" | while read -r line; do
    var="${line%%=*}"
    val="${line#*=}"
    [[ -n "$val" ]] && echo "  ✓ ${var%%_*}"
done | sort -u

echo ""
echo "Run 'make dev' to start local development"
